options:
  merge-default-rules: false

rules:
  attribute-quotes:
    - 2
    - include: true

  bem-depth:
    - 0

  border-zero:
    - 2
    - convention: 'none'

  brace-style:
    - 2
    - style: '1tbs'
    - allow-single-line: false

  class-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'

  clean-import-paths:
    - 0

  empty-args:
    - 2
    - include: true

  empty-line-between-blocks:
    - 2
    - include: true
    - allow-single-line-rulesets: false

  extends-before-declarations:
    - 2

  extends-before-mixins:
    - 2

  final-newline:
    - 2
    - include: true

  force-attribute-nesting:
    - 0

  force-element-nesting:
    - 0

  force-psuedo-nesting:
    - 0

  function-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'

  hex-length:
    - 2
    - style: 'long'

  hex-notation:
    - 2
    - style: 'uppercase'

  id-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'

  indentation:
    - 2
    - size: 2

  leading-zero:
    - 2
    - include: true

  mixin-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'

  mixins-before-declarations:
    - 0

  nesting-depth:
    - 0

  no-attribute-selectors:
    - 0

  no-color-hex:
    - 2

  no-color-keywords:
    - 2

  no-color-literals:
    - 2
    - allow-map-identifiers: false
    - allow-rgba: false
    - allow-variable-identifiers: true

  no-combinators:
    - 0

  no-css-comments:
    - 2

  no-debug:
    - 2

  no-disallowed-properties:
    - 0

  no-duplicate-properties:
    - 2
    - exclude:
      - 'display'
      - 'background-color'
      - 'cursor'
      - 'filter'

  no-empty-rulesets:
    - 2

  no-extends:
    - 0

  no-ids:
    - 0

  no-important:
    - 0

  no-invalid-hex:
    - 2

  no-mergeable-selectors:
    - 2

  no-misspelled-properties:
    - 2
    - extra-properties:
      - '*background'
      - '*background-image'
      - '*display'
      - '*font-family'
      - '_font-family'
      - '*height'
      - '*list-style-image'
      - '*margin-left'
      - '*margin-right'
      - '*overflow'
      - '*position'
      - '*vertical-align'
      - '*width'
      - '*zoom'

  no-qualifying-elements:
    - 0

  no-trailing-whitespace:
    - 2

  no-trailing-zero:
    - 2

  no-transition-all:
    - 2

  no-universal-selectors:
    - 0

  no-url-protocols:
    - 0

  no-vendor-prefixes:
    - 0

  no-warn:
    - 2

  one-declaration-per-line:
    - 2

  placeholder-in-extend:
    - 0

  placeholder-name-format:
    - 2
    - convention: 'hyphenatedlowercase'

  property-sort-order:
    - 2
    - order: 'concentric'

  property-units:
    - 0

  pseudo-element:
    - 2

  quotes:
    - 2
    - style: 'single'

  shorthand-values:
    - 0

  single-line-per-selector:
    - 0

  space-after-bang:
    - 2
    - include: false

  space-after-colon:
    - 2
    - include: true

  space-after-comma:
     - 2
     - include: true

  space-around-operator:
    - 2
    - include: true

  space-before-bang:
    - 2
    - include: true

  space-before-brace:
    - 2
    - include: true

  space-before-colon:
    - 2
    - include: false

  space-between-parens:
    - 2
    - include: false
    - include: false

  trailing-semicolon:
    - 2
    - include: true

  url-quotes:
    - 2

  variable-for-property:
    - 0

  variable-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: 'hyphenatedlowercase'

  zero-unit:
    - 2
    - include: false
