language: node_js
node_js:
  - node

notifications:
  email: false

dist: trusty
sudo: required
addons:
  chrome: stable

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coveralls
